name: Airflow CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: airflow
          POSTGRES_PASSWORD: airflow
          POSTGRES_DB: airflow
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Build Airflow Docker container
      run: docker-compose -f docker-compose.ci.yml up -d

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run tests
      run: |
        docker exec -t airflow-dags_webserver_1 airflow dags list
        pytest airflow-dags/tests/

    - name: Cleanup
      run: docker-compose -f docker-compose.ci.yml down
