name: Airflow CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: airflow
          POSTGRES_PASSWORD: airflow
          POSTGRES_DB: airflow
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Build and start Airflow Docker containers
      run: docker-compose -f docker-compose.ci.yml up -d
    
    - name: Check Docker container statuses
      run: docker ps -a
    
    - name: Fetch Docker container logs
      run: docker logs airflow-dags_webserver_1 || true  # '|| true' ensures the workflow continues even if this command fails
    
    - name: Run Airflow DAG list command
      run: docker exec -t airflow-dags_webserver_1 airflow dags list
    
    - name: Run tests
      run: pytest ./tests/
    
    - name: Cleanup
      run: docker-compose -f docker-compose.ci.yml down
